/**
 * Single registry of test seams. Format: region.component.element.
 * Components must import from here — never inline a data-testid string.
 */
export const testIds = {
  workspace: {
    root: "workspace.layout.root",
    main: "workspace.layout.main",
    splitPane: "workspace.split-pane.root",
    resizeHandle: "workspace.split-pane.handle",
    toolbar: "workspace.toolbar.root",
    fileName: "workspace.toolbar.file-name",
    saveState: "workspace.toolbar.save-state",
    save: "workspace.toolbar.save",
    exportMenu: "workspace.toolbar.export-menu",
    exportSvg: "workspace.toolbar.export-svg",
    exportPng: "workspace.toolbar.export-png",
    exportMarkdown: "workspace.toolbar.export-markdown",
    themeToggle: "workspace.toolbar.theme-toggle",
    settings: "workspace.toolbar.settings",
    agentPanelToggle: "workspace.toolbar.agent-panel-toggle",
    statusBar: "workspace.status-bar.root",
    cursorPosition: "workspace.status-bar.cursor-position",
    mermaidVersion: "workspace.status-bar.mermaid-version",
    diagnosticsCount: "workspace.status-bar.diagnostics-count",
  },
  agentChip: {
    root: "workspace.agent-chip.root",
    label: "workspace.agent-chip.label",
    icon: "workspace.agent-chip.icon",
  },
  editor: {
    host: "editor.host.root",
    toolbar: "editor.toolbar.root",
    wrapToggle: "editor.toolbar.wrap-toggle",
    formatAction: "editor.toolbar.format",
    gutter: "editor.gutter.root",
    gutterLine: "editor.gutter.line",
    errorBadge: "editor.gutter.error-badge",
    scrollContainer: "editor.host.scroll-container",
    mountSlot: "editor.host.mount-slot",
    announcer: "editor.host.announcer",
  },
  preview: {
    root: "preview.pane.root",
    toolbar: "preview.pane.toolbar",
    empty: "preview.pane.empty",
    diagramFrame: "preview.diagram-frame.root",
    captionBar: "preview.diagram-frame.caption-bar",
    blockId: "preview.diagram-frame.block-id",
    diagramType: "preview.diagram-frame.diagram-type",
    mountSlot: "preview.diagram-frame.mount-slot",
    hoverToolbar: "preview.diagram-frame.hover-toolbar",
    copy: "preview.diagram-frame.copy",
    exportSvg: "preview.diagram-frame.export-svg",
    exportPng: "preview.diagram-frame.export-png",
    askAgent: "preview.diagram-frame.ask-agent",
    zoomIn: "preview.diagram-frame.zoom-in",
    zoomOut: "preview.diagram-frame.zoom-out",
    zoomReset: "preview.diagram-frame.zoom-reset",
    zoomFit: "preview.diagram-frame.zoom-fit",
    viewport: "preview.diagram-frame.viewport",
    panReset: "preview.diagram-frame.pan-reset",
    errorCard: "preview.diagram-frame.error-card",
    errorLineRef: "preview.diagram-frame.error-line-ref",
  },
  agent: {
    panel: "agent.panel.root",
    close: "agent.panel.close",
    disconnected: "agent.panel.disconnected",
    connect: "agent.panel.connect",
    transcript: "agent.transcript.root",
    textItem: "agent.transcript.text-item",
    planItem: "agent.transcript.plan-item",
    planStep: "agent.transcript.plan-step",
    toolCall: "agent.transcript.tool-call",
    toolCallStatus: "agent.transcript.tool-call-status",
    streaming: "agent.transcript.streaming",
    liveRegion: "agent.transcript.live-region",
    announcement: "agent.transcript.announcement",
    promptInput: "agent.prompt.input",
    promptSend: "agent.prompt.send",
    contextPill: "agent.prompt.context-pill",
    contextPillRemove: "agent.prompt.context-pill-remove",
    permission: "agent.permission.root",
    permissionTool: "agent.permission.tool",
    permissionTarget: "agent.permission.target",
    allowOnce: "agent.permission.allow-once",
    alwaysSession: "agent.permission.always-session",
    deny: "agent.permission.deny",
    permissionResolved: "agent.permission.resolved",
    diff: "agent.diff.root",
    diffBefore: "agent.diff.before",
    diffAfter: "agent.diff.after",
    diffAccept: "agent.diff.accept",
    diffReject: "agent.diff.reject",
    diffStatus: "agent.diff.status",
  },
  welcome: {
    root: "welcome.page.root",
    openFile: "welcome.actions.open-file",
    recentList: "welcome.recent-files.list",
    recentItem: "welcome.recent-files.item",
    recentEmpty: "welcome.recent-files.empty",
    templateGrid: "welcome.templates.grid",
    templateCard: "welcome.templates.card",
  },
  settings: {
    dialog: "settings.dialog.root",
    theme: "settings.dialog.theme",
    themeOption: "settings.dialog.theme-option",
    mermaidVersion: "settings.dialog.mermaid-version",
    language: "settings.dialog.language",
    cancel: "settings.dialog.cancel",
    save: "settings.dialog.save",
  },
  dev: {
    switcher: "dev.state-switcher.root",
    toggle: "dev.state-switcher.toggle",
    option: "dev.state-switcher.option",
  },
} as const;
