/**
 * Single registry of test seams. Format: region.component.element.
 * Components must import from here — never inline a data-testid string.
 */
export const testIds = {
  workspace: {
    root: "workspace.layout.root",
    main: "workspace.layout.main",
    splitPane: "workspace.splitPane.root",
    resizeHandle: "workspace.splitPane.handle",
    toolbar: "workspace.toolbar.root",
    fileName: "workspace.toolbar.fileName",
    saveState: "workspace.toolbar.saveState",
    exportMenu: "workspace.toolbar.exportMenu",
    exportSvg: "workspace.toolbar.exportSvg",
    exportPng: "workspace.toolbar.exportPng",
    exportMarkdown: "workspace.toolbar.exportMarkdown",
    themeToggle: "workspace.toolbar.themeToggle",
    settings: "workspace.toolbar.settings",
    agentPanelToggle: "workspace.toolbar.agentPanelToggle",
    statusBar: "workspace.statusBar.root",
    cursorPosition: "workspace.statusBar.cursorPosition",
    mermaidVersion: "workspace.statusBar.mermaidVersion",
    diagnosticsCount: "workspace.statusBar.diagnosticsCount",
  },
  agentChip: {
    root: "workspace.agentChip.root",
    label: "workspace.agentChip.label",
    icon: "workspace.agentChip.icon",
  },
  editor: {
    host: "editor.host.root",
    toolbar: "editor.toolbar.root",
    wrapToggle: "editor.toolbar.wrapToggle",
    formatAction: "editor.toolbar.format",
    gutter: "editor.gutter.root",
    gutterLine: "editor.gutter.line",
    errorBadge: "editor.gutter.errorBadge",
    scrollContainer: "editor.host.scrollContainer",
    mountSlot: "editor.host.mountSlot",
  },
  preview: {
    root: "preview.pane.root",
    toolbar: "preview.pane.toolbar",
    empty: "preview.pane.empty",
    diagramFrame: "preview.diagramFrame.root",
    captionBar: "preview.diagramFrame.captionBar",
    blockId: "preview.diagramFrame.blockId",
    diagramType: "preview.diagramFrame.diagramType",
    mountSlot: "preview.diagramFrame.mountSlot",
    hoverToolbar: "preview.diagramFrame.hoverToolbar",
    copy: "preview.diagramFrame.copy",
    exportSvg: "preview.diagramFrame.exportSvg",
    exportPng: "preview.diagramFrame.exportPng",
    askAgent: "preview.diagramFrame.askAgent",
    zoomIn: "preview.diagramFrame.zoomIn",
    zoomOut: "preview.diagramFrame.zoomOut",
    zoomReset: "preview.diagramFrame.zoomReset",
    zoomFit: "preview.diagramFrame.zoomFit",
    errorCard: "preview.diagramFrame.errorCard",
    errorLineRef: "preview.diagramFrame.errorLineRef",
  },
  agent: {
    panel: "agent.panel.root",
    close: "agent.panel.close",
    disconnected: "agent.panel.disconnected",
    connect: "agent.panel.connect",
    transcript: "agent.transcript.root",
    textItem: "agent.transcript.textItem",
    planItem: "agent.transcript.planItem",
    planStep: "agent.transcript.planStep",
    toolCall: "agent.transcript.toolCall",
    toolCallStatus: "agent.transcript.toolCallStatus",
    streaming: "agent.transcript.streaming",
    liveRegion: "agent.transcript.liveRegion",
    announcement: "agent.transcript.announcement",
    promptInput: "agent.prompt.input",
    promptSend: "agent.prompt.send",
    contextPill: "agent.prompt.contextPill",
    contextPillRemove: "agent.prompt.contextPillRemove",
    permission: "agent.permission.root",
    permissionTool: "agent.permission.tool",
    permissionTarget: "agent.permission.target",
    allowOnce: "agent.permission.allowOnce",
    alwaysSession: "agent.permission.alwaysSession",
    deny: "agent.permission.deny",
    permissionResolved: "agent.permission.resolved",
    diff: "agent.diff.root",
    diffBefore: "agent.diff.before",
    diffAfter: "agent.diff.after",
    diffAccept: "agent.diff.accept",
    diffReject: "agent.diff.reject",
    diffStatus: "agent.diff.status",
  },
  welcome: {
    root: "welcome.page.root",
    openFile: "welcome.actions.openFile",
    recentList: "welcome.recentFiles.list",
    recentItem: "welcome.recentFiles.item",
    recentEmpty: "welcome.recentFiles.empty",
    templateGrid: "welcome.templates.grid",
    templateCard: "welcome.templates.card",
  },
  settings: {
    dialog: "settings.dialog.root",
    theme: "settings.dialog.theme",
    themeOption: "settings.dialog.themeOption",
    mermaidVersion: "settings.dialog.mermaidVersion",
    language: "settings.dialog.language",
    cancel: "settings.dialog.cancel",
    save: "settings.dialog.save",
  },
  dev: {
    switcher: "dev.stateSwitcher.root",
    toggle: "dev.stateSwitcher.toggle",
    option: "dev.stateSwitcher.option",
  },
} as const;
